server:
  port: ${PORT:8080}
  address: 0.0.0.0
  ssl:
    enabled: false

jwt:
      issuer: ${JWT_ISSUER}
      secret: ${JWT_SECRET}

spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

app:
  mail:
    from: ${MAIL_FROM}
    from-name: PetCare Scheduler
    base-url: ${MAIL_URL}
    api-key: ${MAIL_KEY}

