spring:
  datasource:
    url: jdbc:h2:mem:petcare;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}

server:
  port: 8443
  ssl:
    enabled: true
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    oauth:
      clientId: swagger
      clientSecret: swagger-secret
      scopes: openid,profile,email