CREATE TABLE tutor (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       first_name VARCHAR(255) NOT NULL,
                       last_name VARCHAR(255),
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL,
                       phone_number VARCHAR(255),
                       avatar VARCHAR(255)
);

CREATE TABLE pet (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name VARCHAR(255) NOT NULL,
                     specie VARCHAR(255) NOT NULL,
                     race VARCHAR(255),
                     birthdate DATE,
                     tutor_id BIGINT REFERENCES tutor(id)
);

CREATE TABLE event (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       type VARCHAR(255) NOT NULL,
                       description VARCHAR(255),
                       date_start TIMESTAMP NOT NULL,
                       frequency VARCHAR(255),
                       interval_count BIGINT,
                       repetitions INTEGER,
                       final_date TIMESTAMP,
                       status VARCHAR(255) NOT NULL,
                       pet_id BIGINT REFERENCES pet(id)
);