-- Ciclo 2: separa a regra recorrente (care_plan) da execução concreta
-- (care_occurrence). A tabela event permanece durante a janela de migração,
-- mas deixa de ser a fonte de verdade das novas telas.
CREATE TABLE care_plan (
    id UUID PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    schedule_revision INTEGER NOT NULL DEFAULT 0,
    tutor_id BIGINT NOT NULL,
    pet_id BIGINT NOT NULL,
    responsible_tutor_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    title VARCHAR(120) NOT NULL,
    instructions VARCHAR(2000),
    start_at TIMESTAMP NOT NULL,
    frequency VARCHAR(16),
    interval_count BIGINT,
    repetitions INTEGER,
    final_date TIMESTAMP,
    reminder_minutes_before INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_care_plan_tutor FOREIGN KEY (tutor_id) REFERENCES tutor(id) ON DELETE CASCADE,
    CONSTRAINT fk_care_plan_pet FOREIGN KEY (pet_id) REFERENCES pet(id) ON DELETE CASCADE,
    CONSTRAINT fk_care_plan_responsible FOREIGN KEY (responsible_tutor_id) REFERENCES tutor(id),
    CONSTRAINT ck_care_plan_type CHECK (type IN ('VACCINE', 'MEDICINE', 'DIARY', 'BREED', 'SERVICE')),
    CONSTRAINT ck_care_plan_title CHECK (CHAR_LENGTH(title) BETWEEN 1 AND 120),
    CONSTRAINT ck_care_plan_revision CHECK (schedule_revision >= 0),
    CONSTRAINT ck_care_plan_interval CHECK (
        (frequency IS NULL AND interval_count IS NULL AND repetitions IS NULL AND final_date IS NULL)
        OR (frequency IS NOT NULL AND interval_count > 0 AND (repetitions IS NULL OR repetitions > 0))
    ),
    CONSTRAINT ck_care_plan_reminder CHECK (reminder_minutes_before BETWEEN 0 AND 10080)
);

CREATE TABLE care_occurrence (
    id UUID PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    plan_id UUID NOT NULL,
    schedule_revision INTEGER NOT NULL,
    tutor_id BIGINT NOT NULL,
    pet_id BIGINT NOT NULL,
    sequence_number INTEGER NOT NULL,
    type VARCHAR(32) NOT NULL,
    title VARCHAR(120) NOT NULL,
    instructions VARCHAR(2000),
    due_at TIMESTAMP NOT NULL,
    status VARCHAR(24) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    completed_by_tutor_id BIGINT,
    completion_note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    legacy_event_id BIGINT UNIQUE,
    CONSTRAINT fk_care_occurrence_plan FOREIGN KEY (plan_id) REFERENCES care_plan(id) ON DELETE CASCADE,
    CONSTRAINT fk_care_occurrence_tutor FOREIGN KEY (tutor_id) REFERENCES tutor(id) ON DELETE CASCADE,
    CONSTRAINT fk_care_occurrence_pet FOREIGN KEY (pet_id) REFERENCES pet(id) ON DELETE CASCADE,
    CONSTRAINT fk_care_occurrence_completed_by FOREIGN KEY (completed_by_tutor_id) REFERENCES tutor(id),
    CONSTRAINT ck_care_occurrence_sequence CHECK (sequence_number >= 0),
    CONSTRAINT ck_care_occurrence_revision CHECK (schedule_revision >= 0),
    CONSTRAINT ck_care_occurrence_type CHECK (type IN ('VACCINE', 'MEDICINE', 'DIARY', 'BREED', 'SERVICE')),
    CONSTRAINT ck_care_occurrence_status CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_care_occurrence_completion CHECK (
        (status = 'COMPLETED' AND completed_at IS NOT NULL AND completed_by_tutor_id IS NOT NULL)
        OR (status <> 'COMPLETED')
    ),
    CONSTRAINT uk_care_occurrence_plan_sequence UNIQUE (plan_id, schedule_revision, sequence_number)
);

CREATE TABLE care_occurrence_action (
    id UUID PRIMARY KEY,
    request_id UUID NOT NULL UNIQUE,
    occurrence_id UUID NOT NULL,
    actor_tutor_id BIGINT NOT NULL,
    action VARCHAR(16) NOT NULL,
    previous_status VARCHAR(24) NOT NULL,
    new_status VARCHAR(24) NOT NULL,
    happened_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_care_action_occurrence FOREIGN KEY (occurrence_id) REFERENCES care_occurrence(id) ON DELETE CASCADE,
    CONSTRAINT fk_care_action_actor FOREIGN KEY (actor_tutor_id) REFERENCES tutor(id),
    CONSTRAINT ck_care_action_type CHECK (action IN ('COMPLETE', 'UNDO', 'CANCEL'))
);

CREATE TABLE care_reminder_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id UUID NOT NULL UNIQUE,
    tutor_id BIGINT NOT NULL,
    tutor_email VARCHAR(255) NOT NULL,
    pet_name VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE,
    attempts INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_care_reminder_occurrence FOREIGN KEY (occurrence_id) REFERENCES care_occurrence(id) ON DELETE CASCADE,
    CONSTRAINT fk_care_reminder_tutor FOREIGN KEY (tutor_id) REFERENCES tutor(id) ON DELETE CASCADE,
    CONSTRAINT ck_care_reminder_attempts CHECK (attempts >= 0)
);

-- UUIDs determinísticos permitem relacionar os registros legados sem depender
-- de funções específicas, preservando o backfill determinístico.
INSERT INTO care_plan (
    id, schedule_revision, tutor_id, pet_id, responsible_tutor_id, type, title, instructions,
    start_at, frequency, interval_count, repetitions, final_date,
    reminder_minutes_before, active, created_at, updated_at
)
SELECT
    CAST(CONCAT('00000000-0000-0000-0001-', RIGHT(CONCAT('000000000000', CAST(e.id AS VARCHAR)), 12)) AS UUID),
    0,
    p.tutor_id,
    e.pet_id,
    p.tutor_id,
    e.type,
    LEFT(COALESCE(NULLIF(TRIM(e.description), ''), e.type), 120),
    NULL,
    e.date_start,
    e.frequency,
    CASE WHEN e.frequency IS NULL THEN NULL ELSE COALESCE(e.interval_count, 1) END,
    CASE
        WHEN e.frequency IS NULL OR e.repetitions IS NULL THEN NULL
        ELSE GREATEST(e.repetitions - e.occurrence_count, 1)
    END,
    e.final_date,
    0,
    CASE WHEN e.status = 'PENDING' THEN TRUE ELSE FALSE END,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM event e
JOIN pet p ON p.id = e.pet_id;

INSERT INTO care_occurrence (
    id, plan_id, schedule_revision, tutor_id, pet_id, sequence_number, type, title, instructions,
    due_at, status, completed_at, completed_by_tutor_id, completion_note,
    created_at, updated_at, legacy_event_id
)
SELECT
    CAST(CONCAT('00000000-0000-0000-0002-', RIGHT(CONCAT('000000000000', CAST(e.id AS VARCHAR)), 12)) AS UUID),
    CAST(CONCAT('00000000-0000-0000-0001-', RIGHT(CONCAT('000000000000', CAST(e.id AS VARCHAR)), 12)) AS UUID),
    0,
    p.tutor_id,
    e.pet_id,
    0,
    e.type,
    LEFT(COALESCE(NULLIF(TRIM(e.description), ''), e.type), 120),
    NULL,
    e.date_start,
    CASE WHEN e.status = 'DONE' THEN 'COMPLETED' ELSE 'SCHEDULED' END,
    CASE WHEN e.status = 'DONE' THEN e.date_start ELSE NULL END,
    CASE WHEN e.status = 'DONE' THEN p.tutor_id ELSE NULL END,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    e.id
FROM event e
JOIN pet p ON p.id = e.pet_id;

-- Lembretes ainda pendentes são transferidos para o novo outbox. O registro
-- antigo é marcado como processado para que os dois relays não enviem em dobro.
INSERT INTO care_reminder_outbox (occurrence_id, tutor_id, tutor_email, pet_name, created_at, sent_at, attempts)
SELECT
    CAST(CONCAT('00000000-0000-0000-0002-', RIGHT(CONCAT('000000000000', CAST(o.event_id AS VARCHAR)), 12)) AS UUID),
    p.tutor_id,
    o.tutor_email,
    o.pet_name,
    o.created_at,
    o.sent_at,
    o.attempts
FROM reminder_outbox o
JOIN event e ON e.id = o.event_id
JOIN pet p ON p.id = e.pet_id;

UPDATE reminder_outbox
SET sent_at = CURRENT_TIMESTAMP
WHERE sent_at IS NULL
  AND EXISTS (SELECT 1 FROM event e WHERE e.id = reminder_outbox.event_id);

CREATE INDEX idx_care_plan_tutor_active ON care_plan(tutor_id, active);
CREATE INDEX idx_care_plan_pet_active ON care_plan(pet_id, active);
CREATE INDEX idx_care_occurrence_tutor_due ON care_occurrence(tutor_id, due_at);
CREATE INDEX idx_care_occurrence_pet_due ON care_occurrence(pet_id, due_at);
CREATE INDEX idx_care_occurrence_status_due ON care_occurrence(status, due_at);
CREATE INDEX idx_care_action_occurrence_time ON care_occurrence_action(occurrence_id, happened_at);
CREATE INDEX idx_care_reminder_pending ON care_reminder_outbox(sent_at, attempts);
