-- ADR-002: expand the care schedule schema before retiring legacy wall-clock columns.
CREATE TABLE care_schedule_migration_issue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(32) NOT NULL,
    entity_id VARCHAR(64) NOT NULL,
    issue_code VARCHAR(64) NOT NULL,
    details VARCHAR(1000) NOT NULL,
    detected_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE care_plan ADD COLUMN zone_id VARCHAR(64);
ALTER TABLE care_plan ADD COLUMN start_at_instant TIMESTAMP WITH TIME ZONE;
ALTER TABLE care_plan ADD COLUMN schedule_kind VARCHAR(32);
ALTER TABLE care_plan ADD COLUMN calendar_unit VARCHAR(16);
ALTER TABLE care_plan ADD COLUMN fixed_interval_seconds BIGINT;
ALTER TABLE care_plan ADD COLUMN daily_times VARCHAR(512);
ALTER TABLE care_plan ADD COLUMN end_at_instant TIMESTAMP WITH TIME ZONE;
ALTER TABLE care_plan ALTER COLUMN repetitions TYPE BIGINT;

UPDATE care_plan p
SET zone_id = COALESCE(h.timezone, 'America/Sao_Paulo')
FROM household h
WHERE h.id = p.household_id;

-- A round-trip mismatch identifies a local time in a DST gap. A neighboring
-- instant resolving to the same local time identifies an overlap. The
-- migration aborts instead of silently choosing a different historical slot.
INSERT INTO care_schedule_migration_issue(entity_type, entity_id, issue_code, details)
SELECT 'CARE_PLAN', p.id::text, 'START_AT_DST_GAP',
       'start_at=' || p.start_at::text || ', zone_id=' || p.zone_id
FROM care_plan p
WHERE ((p.start_at AT TIME ZONE p.zone_id) AT TIME ZONE p.zone_id) <> p.start_at;

INSERT INTO care_schedule_migration_issue(entity_type, entity_id, issue_code, details)
SELECT 'CARE_PLAN', p.id::text, 'START_AT_DST_OVERLAP',
       'start_at=' || p.start_at::text || ', zone_id=' || p.zone_id
FROM care_plan p
WHERE ((p.start_at AT TIME ZONE p.zone_id) - INTERVAL '1 hour') AT TIME ZONE p.zone_id = p.start_at
   OR ((p.start_at AT TIME ZONE p.zone_id) + INTERVAL '1 hour') AT TIME ZONE p.zone_id = p.start_at;

INSERT INTO care_schedule_migration_issue(entity_type, entity_id, issue_code, details)
SELECT 'CARE_PLAN', p.id::text, 'FINAL_DATE_DST_GAP',
       'final_date=' || p.final_date::text || ', zone_id=' || p.zone_id
FROM care_plan p
WHERE p.final_date IS NOT NULL
  AND ((p.final_date AT TIME ZONE p.zone_id) AT TIME ZONE p.zone_id) <> p.final_date;

INSERT INTO care_schedule_migration_issue(entity_type, entity_id, issue_code, details)
SELECT 'CARE_PLAN', p.id::text, 'FINAL_DATE_DST_OVERLAP',
       'final_date=' || p.final_date::text || ', zone_id=' || p.zone_id
FROM care_plan p
WHERE p.final_date IS NOT NULL
  AND (((p.final_date AT TIME ZONE p.zone_id) - INTERVAL '1 hour') AT TIME ZONE p.zone_id = p.final_date
    OR ((p.final_date AT TIME ZONE p.zone_id) + INTERVAL '1 hour') AT TIME ZONE p.zone_id = p.final_date);

UPDATE care_plan
SET start_at_instant = start_at AT TIME ZONE zone_id,
    schedule_kind = CASE WHEN frequency IS NULL THEN 'ONE_TIME' ELSE 'CALENDAR_INTERVAL' END,
    calendar_unit = CASE frequency
        WHEN 'DAILY' THEN 'DAY'
        WHEN 'WEEKLY' THEN 'WEEK'
        WHEN 'MONTHLY' THEN 'MONTH'
        WHEN 'YEARLY' THEN 'YEAR'
        ELSE NULL
    END,
    end_at_instant = CASE WHEN final_date IS NULL THEN NULL ELSE final_date AT TIME ZONE zone_id END;

ALTER TABLE care_plan ALTER COLUMN zone_id SET NOT NULL;
ALTER TABLE care_plan ALTER COLUMN start_at_instant SET NOT NULL;
ALTER TABLE care_plan ALTER COLUMN schedule_kind SET NOT NULL;
ALTER TABLE care_plan ALTER COLUMN start_at DROP NOT NULL;
ALTER TABLE care_plan DROP CONSTRAINT ck_care_plan_interval;
ALTER TABLE care_plan ADD CONSTRAINT ck_care_plan_schedule_v2 CHECK (
    (schedule_kind = 'ONE_TIME' AND calendar_unit IS NULL AND interval_count IS NULL
        AND fixed_interval_seconds IS NULL AND daily_times IS NULL AND repetitions IS NULL AND end_at_instant IS NULL)
 OR (schedule_kind = 'CALENDAR_INTERVAL' AND calendar_unit IN ('DAY', 'WEEK', 'MONTH', 'YEAR')
        AND interval_count > 0 AND fixed_interval_seconds IS NULL AND daily_times IS NULL)
 OR (schedule_kind = 'FIXED_INTERVAL' AND calendar_unit IS NULL AND interval_count IS NULL
        AND fixed_interval_seconds BETWEEN 60 AND 31536000 AND daily_times IS NULL)
 OR (schedule_kind = 'DAILY_TIMES' AND calendar_unit IS NULL AND interval_count IS NULL
        AND fixed_interval_seconds IS NULL AND CHAR_LENGTH(daily_times) > 0)
);
ALTER TABLE care_plan ADD CONSTRAINT ck_care_plan_schedule_bounds_v2 CHECK (
    (repetitions IS NULL OR repetitions > 0)
    AND (end_at_instant IS NULL OR end_at_instant >= start_at_instant)
);

ALTER TABLE care_occurrence ADD COLUMN due_at_instant TIMESTAMP WITH TIME ZONE;
ALTER TABLE care_occurrence ADD COLUMN zone_id VARCHAR(64);

INSERT INTO care_schedule_migration_issue(entity_type, entity_id, issue_code, details)
SELECT 'CARE_OCCURRENCE', o.id::text, 'DUE_AT_DST_GAP',
       'due_at=' || o.due_at::text || ', zone_id=' || p.zone_id
FROM care_occurrence o
JOIN care_plan p ON p.id = o.plan_id
WHERE ((o.due_at AT TIME ZONE p.zone_id) AT TIME ZONE p.zone_id) <> o.due_at;

INSERT INTO care_schedule_migration_issue(entity_type, entity_id, issue_code, details)
SELECT 'CARE_OCCURRENCE', o.id::text, 'DUE_AT_DST_OVERLAP',
       'due_at=' || o.due_at::text || ', zone_id=' || p.zone_id
FROM care_occurrence o
JOIN care_plan p ON p.id = o.plan_id
WHERE ((o.due_at AT TIME ZONE p.zone_id) - INTERVAL '1 hour') AT TIME ZONE p.zone_id = o.due_at
   OR ((o.due_at AT TIME ZONE p.zone_id) + INTERVAL '1 hour') AT TIME ZONE p.zone_id = o.due_at;

UPDATE care_occurrence o
SET due_at_instant = o.due_at AT TIME ZONE p.zone_id,
    zone_id = p.zone_id
FROM care_plan p
WHERE p.id = o.plan_id;

ALTER TABLE care_occurrence ALTER COLUMN due_at_instant SET NOT NULL;
ALTER TABLE care_occurrence ALTER COLUMN zone_id SET NOT NULL;
ALTER TABLE care_occurrence ALTER COLUMN due_at DROP NOT NULL;
ALTER TABLE care_occurrence ALTER COLUMN sequence_number TYPE BIGINT;

INSERT INTO care_schedule_migration_issue(entity_type, entity_id, issue_code, details)
SELECT 'CARE_PLAN_REVISION', plan_id::text || ':' || schedule_revision::text, 'SEQUENCE_GAP',
       'min=' || MIN(sequence_number)::text || ', max=' || MAX(sequence_number)::text || ', count=' || COUNT(*)::text
FROM care_occurrence
GROUP BY plan_id, schedule_revision
HAVING MIN(sequence_number) <> 0 OR COUNT(*) <> MAX(sequence_number) - MIN(sequence_number) + 1;

DO $$
DECLARE issue_summary TEXT;
BEGIN
    SELECT string_agg(entity_type || ':' || entity_id || ':' || issue_code, ', ' ORDER BY id)
    INTO issue_summary
    FROM care_schedule_migration_issue;
    IF issue_summary IS NOT NULL THEN
        RAISE EXCEPTION 'care schedule v2 backfill refused: %', issue_summary;
    END IF;
END $$;

CREATE TABLE care_plan_materialization_cursor (
    plan_id UUID NOT NULL,
    schedule_revision INTEGER NOT NULL,
    next_sequence BIGINT,
    next_due_at_instant TIMESTAMP WITH TIME ZONE,
    materialized_through_instant TIMESTAMP WITH TIME ZONE,
    status VARCHAR(16) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (plan_id, schedule_revision),
    CONSTRAINT fk_care_cursor_plan FOREIGN KEY (plan_id) REFERENCES care_plan(id) ON DELETE CASCADE,
    CONSTRAINT ck_care_cursor_status CHECK (status IN ('ACTIVE', 'EXHAUSTED', 'SUPERSEDED')),
    CONSTRAINT ck_care_cursor_next_slot CHECK (
        (status = 'ACTIVE' AND next_sequence IS NOT NULL AND next_sequence >= 0 AND next_due_at_instant IS NOT NULL)
        OR (status <> 'ACTIVE' AND next_sequence IS NULL AND next_due_at_instant IS NULL)
    ),
    CONSTRAINT ck_care_cursor_progress CHECK (
        materialized_through_instant IS NULL OR next_due_at_instant IS NULL
        OR next_due_at_instant > materialized_through_instant
    )
);

WITH materialized AS (
    SELECT p.id AS plan_id, p.schedule_revision, p.schedule_kind, p.calendar_unit,
           p.interval_count, p.repetitions, p.end_at_instant, p.zone_id, p.start_at_instant,
           COALESCE(MAX(o.sequence_number), -1) + 1 AS next_sequence,
           MAX(o.due_at_instant) AS materialized_through
    FROM care_plan p
    LEFT JOIN care_occurrence o ON o.plan_id = p.id AND o.schedule_revision = p.schedule_revision
    WHERE p.active = TRUE
    GROUP BY p.id, p.schedule_revision, p.schedule_kind, p.calendar_unit, p.interval_count,
             p.repetitions, p.end_at_instant, p.zone_id, p.start_at_instant
), candidates AS (
    SELECT m.*,
           CASE
               WHEN materialized_through IS NULL THEN start_at_instant
               WHEN schedule_kind = 'ONE_TIME' THEN NULL
               WHEN calendar_unit = 'DAY' THEN
                   ((materialized_through AT TIME ZONE zone_id) + make_interval(days => interval_count::int)) AT TIME ZONE zone_id
               WHEN calendar_unit = 'WEEK' THEN
                   ((materialized_through AT TIME ZONE zone_id) + make_interval(days => (interval_count * 7)::int)) AT TIME ZONE zone_id
               WHEN calendar_unit = 'MONTH' THEN
                   ((materialized_through AT TIME ZONE zone_id) + make_interval(months => interval_count::int)) AT TIME ZONE zone_id
               WHEN calendar_unit = 'YEAR' THEN
                   ((materialized_through AT TIME ZONE zone_id) + make_interval(years => interval_count::int)) AT TIME ZONE zone_id
               ELSE NULL
           END AS candidate_due_at
    FROM materialized m
), bounded AS (
    SELECT c.*,
           CASE
               WHEN candidate_due_at IS NULL THEN NULL
               WHEN repetitions IS NOT NULL AND next_sequence >= repetitions THEN NULL
               WHEN end_at_instant IS NOT NULL AND candidate_due_at > end_at_instant THEN NULL
               ELSE candidate_due_at
           END AS next_due_at
    FROM candidates c
)
INSERT INTO care_plan_materialization_cursor(
    plan_id, schedule_revision, next_sequence, next_due_at_instant,
    materialized_through_instant, status, updated_at
)
SELECT plan_id, schedule_revision,
       CASE WHEN next_due_at IS NULL THEN NULL ELSE next_sequence END,
       next_due_at, materialized_through,
       CASE WHEN next_due_at IS NULL THEN 'EXHAUSTED' ELSE 'ACTIVE' END,
       CURRENT_TIMESTAMP
FROM bounded;

ALTER TABLE care_reminder_outbox ADD COLUMN cancelled_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE care_escalation_outbox ADD COLUMN cancelled_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE care_escalation_outbox ADD COLUMN due_at_instant TIMESTAMP WITH TIME ZONE;
UPDATE care_escalation_outbox e
SET due_at_instant = e.due_at AT TIME ZONE p.zone_id
FROM care_occurrence o
JOIN care_plan p ON p.id = o.plan_id
WHERE o.id = e.occurrence_id;
ALTER TABLE care_escalation_outbox ALTER COLUMN due_at_instant SET NOT NULL;
ALTER TABLE care_escalation_outbox ALTER COLUMN due_at DROP NOT NULL;

DO $$
DECLARE constraint_name TEXT;
BEGIN
    SELECT c.conname INTO constraint_name
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    WHERE t.relname = 'care_reminder_outbox' AND t.relnamespace = current_schema()::regnamespace AND c.contype = 'u'
      AND pg_get_constraintdef(c.oid) LIKE '%(occurrence_id)%'
    LIMIT 1;
    IF constraint_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE care_reminder_outbox DROP CONSTRAINT %I', constraint_name);
    END IF;

    constraint_name := NULL;
    SELECT c.conname INTO constraint_name
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    WHERE t.relname = 'care_escalation_outbox' AND t.relnamespace = current_schema()::regnamespace AND c.contype = 'u'
      AND pg_get_constraintdef(c.oid) LIKE '%(occurrence_id)%'
    LIMIT 1;
    IF constraint_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE care_escalation_outbox DROP CONSTRAINT %I', constraint_name);
    END IF;
END $$;

CREATE UNIQUE INDEX uk_care_reminder_outbox_active_occurrence
    ON care_reminder_outbox(occurrence_id) WHERE cancelled_at IS NULL;
CREATE UNIQUE INDEX uk_care_escalation_outbox_active_occurrence
    ON care_escalation_outbox(occurrence_id) WHERE cancelled_at IS NULL;
CREATE INDEX idx_care_cursor_active ON care_plan_materialization_cursor(status, updated_at);
CREATE INDEX idx_care_occurrence_household_due_instant ON care_occurrence(household_id, due_at_instant);
CREATE INDEX idx_care_occurrence_status_due_instant ON care_occurrence(status, due_at_instant);
