-- Outbox de lembretes: a detecção diária só enfileira aqui; a entrega de
-- fato (com retry) é feita por um relay separado. UNIQUE(event_id) garante
-- que um mesmo evento nunca recebe duas mensagens, mesmo se a varredura
-- rodar mais de uma vez para o mesmo dia.
CREATE TABLE reminder_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL UNIQUE REFERENCES event(id) ON DELETE CASCADE,
    tutor_email VARCHAR(255) NOT NULL,
    pet_name VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE,
    attempts INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_reminder_outbox_pending ON reminder_outbox(sent_at, attempts);
